landing_penguin/landing_penguin/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from .views import ppt
from arii.views import arii, submit

urlpatterns = [
    path('ppt', ppt, name='ppt'),
    path('arii', arii, name='arii'),
    path('arii-submit', submit, name='arii-submit'),
    path('', include('release.urls')),
    re_path('^', include('main.urls')),
]

main/urls.py
from django.urls import re_path

from . import views

urlpatterns = [
    re_path('^', views.main, name='main'),
]

release/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views

app_name = 'release'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('recruiting', views.recruiting, name='recruiting'),
]

urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from views import ppt
from arii.views import arii, submit

urlpatterns = [
    path('ppt', ppt, name='ppt'),
    path('arii', arii, name='arii'),
    path('arii-submit', submit, name='arii-submit'),
    path('', include('release.urls')),
    re_path('^', include('main.urls')),
]

arii/models.py
from django.db import models

class Post(models.Model):
    string = models.TextField()

main/models.py
from django.db import models

# Create your models here.

release/models.py
from django.db import models

# Create your models here.

arii/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from arii.models import Post

def arii(request):
    posts = Post.objects.all()
    posts.reverse()
    return render(request, 'arii/index.html', {'posts': posts})

def submit(request):
    try:
        string = request.POST['comment']
        post = Post(string=string)
        post.save()
    except:
        pass
    
    return HttpResponseRedirect(reverse('arii'))

main/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'main/main.html', {})

release/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'release/index.html', {})

def about(request):
    return render(request, 'release/about.html', {})

def recruiting(request):
    return render(request, 'release/recruiting.html', {})

views.py
import mimetypes, os
from django.http import HttpResponse
from django.utils.encoding import smart_str

def respond_as_attachment(request, file_path, original_filename):
    fp = open(file_path, 'rb')
    response = HttpResponse(fp.read())
    fp.close()
    type, encoding = mimetypes.guess_type(original_filename)
    if type is None:
        type = 'application/octet-stream'
    response['Content-Type'] = type
    response['Content-Length'] = str(os.stat(file_path).st_size)
    if encoding is not None:
        response['Content-Encoding'] = encoding

    # To inspect details for the below code, see http://greenbytes.de/tech/tc2231/
    if u'WebKit' in request.META['HTTP_USER_AGENT']:
        # Safari 3.0 and Chrome 2.0 accepts UTF-8 encoded string directly.
        filename_header = 'filename=%s' % original_filename.encode('utf-8')
    elif u'MSIE' in request.META['HTTP_USER_AGENT']:
        # IE does not support internationalized filename at all.
        # It can only recognize internationalized URL, so we do the trick via routing rules.
        filename_header = ''
    else:
        # For others like Firefox, we follow RFC2231 (encoding extension in HTTP headers).
        filename_header = 'filename*=UTF-8\'\'%s' % urllib.quote(original_filename.encode('utf-8'))
    filename_header="filename={}".format(original_filename)
    response['Content-Disposition'] = 'attachment; ' + filename_header
    return response

def ppt(request):
    return respond_as_attachment(request, "/home/honamgyu/release2018.pdf", "Release 2018.pdf")

arii/templates/arii/index.html
{% load static %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main/reset.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/arii/index.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
	<div class="content-container">
        <div class="background">
            <img class="background" src="{% static 'img/arii/background.jpg' %}" />
        </div>
		<div class="content">
			<img class="arii-logo" src="{% static 'img/arii/arii-logo.png' %}" />
			<h1 class="arii-title">arii</h1>
            <p class="arii-text">동아리 관리가 힘들었다.<br/>그래서 앱을 만들거다. 아리.</p>
            <button class="button" onclick="window.scrollTo(0, 1000)">개발 훈수 두기</button>
		</div>
        <div class="top">
            <div class="top-button">
                개발자 이야기
            </div>
            <div class="top-button">
                또 뭐있지
            </div>
            <div class="top-button">
                네이버 사랑해요
            </div>
        </div>
	</div>
    <div class="bottom-container">
        <h2 class="header">
            개발 훈수 두기
        </h2>
        <p class="dev-text">
            개발자 왈) 앱을 만들기 전에 다른 동아리 임원진들은 어떤 어려움을 겪는지, 또 부원들은 임원진에게 어떤 불만이 있는지 알고 싶어요! 그래야 의미있는 동아리 앱을 만들죠!
        </p>
        <p class="dev-text">
            임원이나 부원으로서 털어내고 싶은 불만이 있거나 앱에 어떤 기능이 들어갔으면 한다 하는 바램이 있으면 맘껏 얘기해주세요!
        </p>
        <form name='comment' action="{% url 'arii-submit' %}" method="POST">
            {% csrf_token %}
            <input class="form" type="text" name="comment" id="comment" placeholder="여기다 맘껏 입력해주세요!" />
        {% for post in posts %}
            <p class="comment"><span class="comment-number">{{  forloop.counter }}</span>{{ post.string }}</p>
        {% endfor %}
    </div>
	</form>
</body>

main/templates/main/main.html
{% load static %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'css/main/reset.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/main/main.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
	<div class="content-container">
		<div class="content">
			<img class="release-logo" src="{% static 'img/main/release-white.png' %}" />
			<p class="release-text">Welcome to Release</p>
		</div>
	</div>
</body>

release/templates/release/about.html
{% extends 'release/base.html' %}
{% load static %}

{%  block head %}
<link rel="stylesheet" type="text/css" href="{%  static 'release/css/style.css' %}" />
{%  endblock %}


{% block content %}
<div class="text container">
	<div class="text row justify-content-center">
		<div class="text col-10 col-md-8">
			<h1 class="text-header">릴리즈는?</h1>
			<p class="text-content">Release는 학교 공부 외에 자기가 정말 하고 싶은 뭔가를 해보자는 목적으로 설립된 학회입니다.</p>
			<p class="text-content">학회원끼리 정기적으로 <Release Day> 세미나 행사를 열어 자신이 공부하는 내용이나 진행중인 프로젝트 등을 공유하고, Release 내에서 팀을 꾸려 스터디 또는 프로젝트를 진행하기도 합니다.</p>
			<p class="text-content">초급자를 위한 C세미나, 선배님 초청 세미나, 기업 스폰서 해커톤 등 기타 활동도 활발하게 이루어지고 있습니다.</p>
			<h1 class="text-header">2017년 주요 활동</h1>
			<p class="text-content text-content--list">- Release Day: 정기 세미나 행사</p>
			<p class="text-content text-content--list">- [Naver D2] Release World: 대규모 세미나 행사</p>
			<p class="text-content text-content--list">- Google PM 재직 선배님 댁 방문 세미나</p>
			<p class="text-content text-content--list">- IEEE 밤샘 코딩 대회 w/ ACM-ICPC (100위권 2팀)</p>
			<p class="text-content text-content--list">- [MS Student Partners] AI WINTER</p>
			<p class="text-content text-content--list">- [MS Student Partners] MASTERING GOMOKU</p>
			<p class="text-content text-content--list">- Arii: 동아리 관리 서비스 프로젝트 WEB + APP</p>
			<p class="text-content text-content--list">- 코딩 인터뷰 스터디</p>
			<h1 class="text-header">영상: Release World 2017</h1>
			<iframe class="text-video" src="https://www.youtube.com/embed/2pWFD1JJlWo?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
			<h1 class="text-header">IMAGES</h1>
			<img class="text-image" src="{% static 'release/img/image-0.jpg' %}" />
			<img class="text-image" src="{% static 'release/img/image-1.jpg' %}" />
			<img class="text-image" src="{% static 'release/img/image-2.jpg' %}" />
			<img class="text-image" src="{% static 'release/img/image-3.jpg' %}" />
			<img class="text-image" src="{% static 'release/img/image-4.jpg' %}" />
			<img class="text-image" src="{% static 'release/img/image-5.jpg' %}" />
			<h1 class="text-header">연락처</h1>
			<p class="text-content">학회장 16학번 허남규: 010-3307-8419</p>
		</div>
	</div>
</div>
{% endblock %}

release/templates/release/base.html
{% load static %}

<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

		{% block head %}
		{% endblock %}
	</head>
	<body>
		<div class="content-container">
			{% block content %}
			{% endblock %}
		</div>
		<div class="background-container--innerMargin">
			<div class="background-container--outerMargin">
				<div class="background-image">
				</div>
			</div>
		</div>

		<!-- JS for Bootstrap -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<script src="{% static 'release/js/release.js' %}"></script>
	</body>
</html>

release/templates/release/index.html
{% extends 'release/base.html' %}
{% load static %}

{%  block head %}
<link rel="stylesheet" type="text/css" href="{%  static 'release/css/style.css' %}" />
{%  endblock %}


{% block content %}
<div class="hero container">
	<div class="hero row align-items-center justify-content-center">
		<div class="hero col">
			<img class="hero-logo" src="{% static 'release/img/logo.png' %}" />
			<h1 class="hero-name">Release</h1>
			<h2 class="hero-copy">"컴공까지 왔는데</br>진짜 하고 싶은걸 해봐야지."</h2>
			<div class="hero-buttons row justify-content-center">
				<div class="hero-buttons col-8 col-md-6 col-lg-4 col-xl-3">
					<a href="{% url 'release:recruiting' %}" class="hero-recruitingButton">신입 모집 안내</a>
				<a href="{% url 'release:about' %}" class="hero-aboutButton">학회 소개</a>
				</div>
			</div>
			<div class="sns-row row justify-content-center">
				<a href="https://www.facebook.com/SGRelease/"><img class="sns-icon" src="{% static 'release/img/facebook.png' %}" /></a>
				<a href="mailto:sogangrelease@gmail.com"><img class="sns-icon" src="{% static 'release/img/mail.png' %}" /></a>
			</div>
		</div>
	</div>
</div>
</div>
<div class="copyright">Copyright © 2018 Sogang Release. All rights reserved.</div>
{% endblock %}

release/templates/release/recruiting.html
{% extends 'release/base.html' %}
{% load static %}

{%  block head %}
<link rel="stylesheet" type="text/css" href="{%  static 'release/css/style.css' %}" />
{%  endblock %}


{% block content %}
<div class="text container">
	<div class="text row justify-content-center">
		<div class="text col-10 col-md-8">
			<h1 class="text-header">2018년 상반기 모집 일정</h1>
			<p class="text-content">올해 신입 부원 모집은 2/26 (월) - 3/7 (수)으로 예정되어 있습니다.</p>
			<p class="text-content">자세한 사항은 결정되는대로 페이스북, 단톡방, 공식 사이트를 통해 공지할 예정입니다.</p>
			<h1 class="text-header">사전 안내</h1>
			<p class="text-content">준비중...</p>
		</div>
	</div>
</div>
{% endblock %}